---
title: "rSocialWatcher"
#author: "Rob Marty"
#date: "`r Sys.Date()`"
#output: rmarkdown::html_vignette
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r init, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Setup

First, we load relevant packages and create variables for our Facebook API keys.

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
## Load Google Traffic package
library(rSocialWatcher)

## Load packages for working with and visualizing data
library(tidyverse)

library(dplyr)
library(lubridate)
library(jsonlite)
library(httr)
library(stringr)

library(knitr)
library(kableExtra)

## Set Facebook Keys
TOKEN        <- "TOKEN-HERE"
CREATION_ACT <- "CREATION-ACT-HERE"
VERSION      <- "VERSION-HERE"
```

```{r loadkey, include=FALSE}
## Load keys
api_keys <- read.csv("~/Dropbox/World Bank/Webscraping/Files for Server/api_keys.csv",
                     stringsAsFactors = F)

api_keys <- api_keys %>%
  dplyr::filter(Service == "facebook_marketing_ad",
                Details == "robmarty3@gmail.com")

TOKEN <- api_keys %>% 
  dplyr::filter(Account == "token") %>% 
  pull(Key)

CREATION_ACT <- api_keys %>% 
  dplyr::filter(Account == "creation_act") %>% 
  pull(Key) %>% 
  str_replace_all("ACT_", "") 

VERSION <- api_keys %>% 
  dplyr::filter(Account == "version") %>% 
  pull(Key)
```

# Querying Location Data using Different Units

## Around a coordinate

```{r coord_1, include=TRUE, warning=FALSE, message=FALSE}

df_out <- query_fb_marketing_api(location_type = "coordinates",
                                 lat_lon       = c(38.90, -77.01),
                                 radius        = 10,
                                 radius_unit   = "kilometer",
                                 version       = VERSION, 
                                 creation_act  = CREATION_ACT, 
                                 token         = TOKEN)

df_out %>% 
  kable() %>% 
  kable_styling() %>% 
  scroll_box(width = "100%")
```

## Using a location type/key

We can also query using 

```{r coord_1, include=TRUE, warning=FALSE, message=FALSE}

country_df <- get_fb_parameter_ids(type = "country",
                                   version = VERSION,
                                   token = TOKEN)

country_df %>%
  head() %>%
  kable() %>% 
  kable_styling() %>% 
  scroll_box(width = "100%")

df_out <- query_fb_marketing_api(location_type = "country_groups",
                                     location_keys = "US",
                                     version = VERSION, 
                                     creation_act = CREATION_ACT, 
                                     token = TOKEN)


df_out %>% 
  kable() %>% 
  kable_styling() %>% 
  scroll_box(width = "100%")
```
